# Null vector of size 10

In [2]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Find memory size of any array

In [10]:
x = np.zeros((4))
print(x.size*x.itemsize)

32


# Create a vector with values ranging from 10 to 49

In [12]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Reverse a vector

In [31]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
np.flip(x,0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Create a 3*3 matrix with values ranging from 0 to 8

In [22]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [23]:
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Create a 3x3x3 array with random values

In [26]:
x = np.random.random((3,3,3))
print(x)

[[[0.69521621 0.72521141 0.92866289]
  [0.51191937 0.63773286 0.17284735]
  [0.75959561 0.89639324 0.94099671]]

 [[0.56837781 0.88910083 0.85853091]
  [0.2803356  0.74040703 0.31282982]
  [0.63152495 0.85823659 0.06716737]]

 [[0.09948936 0.28908884 0.69430777]
  [0.04527963 0.17086879 0.90175447]
  [0.19053446 0.00742881 0.9501716 ]]]


# Multiply a 5x3 matrix by a 3x2 matrix

In [27]:
y = np.arange(15).reshape(5,3)
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [33]:
z = np.arange(6).reshape(3,2)
print(z)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
x = np.dot(y,z)
print(x)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


# Create a random vector of size 10 and sort it

In [35]:
x = np.random.random(10)
print(x)

[0.26780637 0.67089489 0.49515546 0.20504247 0.64939579 0.87461532
 0.13618469 0.29941563 0.09739969 0.96399489]


In [40]:
print(np.sort(x))

[0.09739969 0.13618469 0.20504247 0.26780637 0.29941563 0.49515546
 0.64939579 0.67089489 0.87461532 0.96399489]


# Subtract the mean of each row of a matrix

In [44]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
y = x.mean(axis = 1,keepdims = True)
print(y)

[[1.]
 [4.]
 [7.]]


In [49]:
z = x - y
print(z)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# Create a random vector of size 10 and replace the maximum value by 0

In [55]:
x = np.random.random(10)
print(x)

[0.25963148 0.70368938 0.65349124 0.02463166 0.56293029 0.4498686
 0.25859881 0.60163383 0.53465475 0.16002835]


In [56]:
x.max()

0.703689382783908

In [57]:
x[x.argmax()] = 0
print(x)

[0.25963148 0.         0.65349124 0.02463166 0.56293029 0.4498686
 0.25859881 0.60163383 0.53465475 0.16002835]
